#!/bin/sh
mkdir Metrics_May11_2017
cp -pr plots/ztable.html Metrics_May11_2017/.
cp -pr plots/authActiveNew.png Metrics_May11_2017/.
cp -pr plots/authPasOnlyNew.png Metrics_May11_2017/.
cp -pr plots/authPublished+PAS-Only-PUB+ActiveNew.png Metrics_May11_2017/.
cp -pr plots/authPublished+PAS-Only-PUBNew.png Metrics_May11_2017/.
cp -pr plots/authPublishedNew.png Metrics_May11_2017/.
cp -pr plots/CADIentriesMany.png Metrics_May11_2017/.
cp -pr plots/LPCNumScholarsActive.png Metrics_May11_2017/.
cp -pr plots/LPCNumScholarsPASOnly.png Metrics_May11_2017/.
cp -pr plots/LPCNumScholarsPublished_PAS_Active.png Metrics_May11_2017/.
cp -pr plots/LPCNumScholarsPublished_PAS.png Metrics_May11_2017/.
cp -pr plots/LPCNumScholarsPublished.png Metrics_May11_2017/.
cp -pr plots/LPCScholarsActive.png Metrics_May11_2017/.
cp -pr plots/LPCScholarsPASOnly.png Metrics_May11_2017/.
cp -pr plots/LPCScholarsPublished_PAS_Active.png Metrics_May11_2017/.
cp -pr plots/LPCScholarsPublished_PAS.png Metrics_May11_2017/.
cp -pr plots/LPCScholarsPublished.png Metrics_May11_2017/.
cp -pr plots/majAuthActiveNew.png Metrics_May11_2017/.
cp -pr plots/majAuthPasOnlyNew.png Metrics_May11_2017/.
cp -pr plots/majAuthPublished+PAS-Only-PUB+ActiveNew.png Metrics_May11_2017/.
cp -pr plots/majAuthPublished+PAS-Only-PUBNew.png Metrics_May11_2017/.
cp -pr plots/majAuthPublishedNew.png Metrics_May11_2017/.
cp -pr plots/signifAuthActive.png Metrics_May11_2017/.
cp -pr plots/signifAuthPasOnly.png Metrics_May11_2017/.
cp -pr plots/signifAuthPublished.png Metrics_May11_2017/.
cp -pr plots/signifAuthPublished+PAS-Only-PUB.png Metrics_May11_2017/.
cp -pr plots/signifAuthPublished+PAS-Only-PUB+ActiveNew.png Metrics_May11_2017/.
